### ISSUE TITLE
Clean polls logic and remove it from the Groups BB

### ISSUE THREAD

**Issue by mdryankov** [rokwire/groups-building-block#150]
### Context
Original discussion:

>[Stephen Hurwit] [12:29 PM, May 16th]
>Mark and I have been discussing the issue about the dependency between the Groups and Polls BBs. I think this is a very important discussion and everyone brought up great points to consider. I think there are really two different topics that are involved, and it was helpful to me to separate them for the moment.
>
> The first topic is a philosophical discussion around the organization of our BBs/services and the way that they should communicate or depend on each other. We have been trying to keep our BBs entirely independent and avoid communication between them as much as possible. While I do think that communication like this should be avoided when possible, I also think there are cases where this needs to happen, and as the system grows we will need a strategy to ensure this communication is efficient and reliable. I have opened an issue here https://github.com/rokwire/core-building-block/issues/496 to track this discussion and re-evaluate periodically. For the moment, however, I still do not believe that any major change in strategy will be necessary to resolve the issues being raised here.
>
> This brings me to the second topic, which is the architecture of features across microservices. My current understanding is that the root of this issue is the relationship between the Groups BB and the Polls BB needed to support Group Poll and Sub-group Poll functionality. As Petyo brought up, we do have "fundamental" services that are explicitly built to provide support and functionality for other services to access (eg. Core BB, Notification BB), as well as "feature" services which are primarily built to provide back-end functionality for client features. However, I do not believe that this distinction is absolute. In other words, all services have the ability to provide features to the clients, as well as other services. In this particular case, I actually view the Groups BB as a mix of "fundamental" and "feature" services. It is worth noting that the Core BB is actually similar since it does provide many "features" to the client as well as "fundamental" functionality for other services as well.
>
> The major issue that Mladen identified is that currently there is interdependency between the Groups BB and the Polls BB, and that both of these BBs are sharing responsibility for the Group Poll functionality and data. I believe we can effectively reorganize this integration to make the Groups BB purely a dependency for the Polls BB, and not vice versa. In other words, the Groups BB should have no knowledge of Polls, or similar concepts managed by other BBs (eg. events). Instead, the Groups BB should simply provide "fundamental" functionality to other BBs which enables them to implement "Group" features.
>
> In this case, we would like to implement Group Polls, which fundamentally are Polls associated with a Group. Since the primary feature in question is a Poll, the Polls BB should be fully responsible for managing these elements. In order to do so, the Polls BB must rely on the Groups BB as a dependency for this feature only. We should therefore remove all "poll" APIs/models/data from the Groups BB. When a new Group Poll is created, a request should be sent to the Polls BB only including the Poll data and the associated Group ID. The Polls BB should then store this data and association.
>
> When a user would like to access their Polls, they will send a request to the Polls BB. The Polls BB must then send a request to the Groups BB to determine which Groups this user is a member of. The Polls BB can then retrieve all Polls associated with these groups, or verify that the user is a member of the Group associated with the requested Poll. Note that this is very similar to the way that the Events BB currently manages access to Group Events, and in fact, the same "internal" (/bbs) endpoints can be used. As a side note, we are almost finished with the Service Account (https://github.com/rokwire/core-building-block/wiki/Concepts#service-accounts) functionality in the Core BB and auth library that should be used in place of these "internal" keys in the future. I will provide updates on this when we are done with the remaining work. In order to improve efficiency, we could also cache the group memberships within the Polls BB.
>
> As for the Sub-group Polls, I am not sure that much has to change. Again, the Polls BB should be fully responsible for managing these. The way I see it, there are two options. We could create a sub-group concept in the Groups BB, which would essentially just be a Group with a Parent Group ID, which the Polls BB could then link exactly the same way as normal Groups. If we choose this path, we should reuse these sub-groups for the posts... etc. Alternatively, instead of thinking of these as Sub-group Polls, we could think of these as Private Polls. In this case, we can simply include a list of User IDs in the Poll that are allowed to access this Poll. This Poll may or may not be associated with a Group, but either way it will only be accessible to users in this list.
>
> I know there is a lot of information here, and that there are many big changes and concepts that are involved. If anything is unclear, or you have any questions please let me know. Please also let me know if I am misunderstanding or overlooking any issues or use-cases that you are aware of, or if you see any issues in the architectural or convention suggestions I made here.

> [Petyo]
 [7:51 AM, May 17th]
> As general here there is no strong right solution as when we achieve something we achieve it at the expense of another.
> Indeed your solution seems the most logical at this point but we would like to extend it with some constraints. I will describe below why we would like to set up these constraints but let me first explain what we mean.
> We differentiate the following types/levels of building blocks based on your suggestions:
> - fundamental level(no changes here) - Core BB and Notifications BB.
> - mixed level(NEW) - Groups BB. Mixed level ones can only depend on fundamental level ones. They cannot depend on feature or mixed levels BBs.
> - feature level(no changes here) - Polls BB, Transportation BB etc. These BBs can depend only on fundamental or mixed levels BBs. They cannot depend on another feature BB.
>
> We would like to set up these constraints as we know what will happen. This is just the beginning of inter-service communication and our worries are that these inter-service communications will not be exceptions but they will become massive. Taking this into account we will end up with an infrastructure which is uncontrollable - something like this(see the pic bellow). This is why we need a hierarchical categorisation of dependency between the building blocks now. For the case we have Polls BB is a feature level BB. Groups BB is mixed level BB. Polls BB depends on Groups BB. Groups BB can depend only on Core or Notification BBs.
> We think that the suggested solution by you and the constraints added above is an acceptable way to go ahead.

> [Mladen]
 [8:04 AM, May 17th]
>  I like this approach “Alternatively, instead of thinking of these as Sub-group Polls, we could think of these as Private Polls. In this case, we can simply include a list of User IDs in the Poll that are allowed to access this Poll. This Poll may or may not be associated with a Group, but either way it will only be accessible to users in this list.” , because everything will be packed on a single place. Something like designed limitation - the poll member list will be independent to user list which will control the poll visibility for the users
> [8:05]
> I’m in agreement with the both comments in case we decide to go ahead with the approach polls bb to depend on groups bb with some restrictions

> [Stephen Hurwit]  [10:55 AM, May17th]
> As discussed on the call I think both of your points are good. I think the constraints you suggested will definitely keep the system simpler and more manageable. Let's try following the model described above and discuss again if any more related issues come up. As far as the sub-group/private polls go, I agree that the "private" poll model is probably fits our requirements better. Thanks again!

**Comment by shurwit** [comment]
Related to #140
