### ISSUE TITLE
[TASK] Store group stats

### ISSUE THREAD

**Issue by shurwit** [rokwire/groups-building-block#227]
### Description
Currently group stats are queried directly from the database every time they are retrieved. This is a very complicated and expensive database operation that will be performed constantly whenever any user accesses any group data. 

### Acceptance Criteria
It would be much more efficient to store the group stats in the group record and update them whenever a member is added/removed/updated.

**Comment by mdryankov** [comment]
@shurwit , this makes sense and will reduce the amount of requests. The trade off would be the slow create/update/delete membership, because the group stats must be updated/regenrated. The retrieve operation would be faster

**Comment by mdryankov** [comment]
@shurwit, this may be incorporated within #238 if the transition refactoring will miss the current release

**Comment by shurwit** [comment]
> @shurwit , this makes sense and will reduce the amount of requests. The trade off would be the slow create/update/delete membership, because the group stats must be updated/regenrated. The retrieve operation would be faster

Hi @mdryankov, yes there is a tradeoff however the update operations will be only slightly more expensive and happen much more infrequently than reads. The read operation happens constantly across all of the clients in the system whenever users access the groups panels.

> @shurwit, this may be incorporated within #238 if the transition refactoring will miss the current release. In other words the migration will include the stats generation. 

Yes we will skip the refactoring for the current release so you can definitely address this in #238 if that makes the most sense. Thanks!

**Comment by mdryankov** [comment]
@shurwit this was implemented along with #238. 

There is a test migration on groupsdb_migration database. which is a clone of the original dev groups & group_memberships  collections.
