### ISSUE TITLE
[FEATURE] Finish the transition process of splitting the group record and membership list on two separate collections

### ISSUE THREAD

**Issue by mdryankov** [rokwire/groups-building-block#238]
**Is your feature request related to a problem? Please describe.**
Finish the transition process of splitting the group record and membership list on two separate collections.
The current state fixes only the bigger groups and this is an attempt to bring this transition to the end

**Describe the solution you'd like**
We should migrate all of the old embedded memberships to the new group_memberships collection and update all APIs to look for memberships in this collection.

**Comment by mdryankov** [comment]
CC @shurwit

**Comment by shurwit** [comment]
Hi @mdryankov, I have pushed some changes to the linked branch (238-migrate-group-memberships). I believe the `synchronizeAuthmanGroup` function is mostly correct at this point, but we still need to handle the admin components currently in the `synchronizeAuthman` function. As we are doing this we may want to consider addressing #214 and #213. 

I do think it will be challenging to split up the migration and the rework of the implementation since they will be likely to impact each other. 

The big challenge here will be to do this in a way that is backwards compatible with all existing APIs (both v1 and v2...). 

You are welcome to pick up where I left off here, or leave this one to me and work on one of the other issues I opened on this repo. Whatever you pick just let me know so we don't accidentally work on the same thing. Thanks!

**Comment by mdryankov** [comment]
Thanks @shurwit. Today I reworked the storage. 
1. The legacy membership storage methods are now using the group_membership collection 
2. The legacy endpoints checks for user membership through the new new Find interfaces
3. Temporary removed the group.Members as a guideline and all reds (compile issues) have been rewritten. Note that the group.Members is still available for backward compatibility.

Remaining or unfinished stuff:
1. Update the legacy endpoints (include members list for get groups & get user groups)
2. Rewrite Authman sync from the scratch. The legacy code has been designed to update the entire members list as a single query. Now this is not the case. 

Perhaps Monday would be a target to finish the rough work and make some integrity checks and test 

P.S I noticed the new membership admin flag. We need to be careful due to the existing clients and I would suggest to pass few back and forth before going in that direction.

**Comment by shurwit** [comment]
> Thanks @shurwit. Today I reworked the storage.
> 
> 1. The legacy membership storage methods are now using the group_membership collection
> 2. The legacy endpoints checks for user membership through the new new Find interfaces
> 3. Temporary removed the group.Members as a guideline and all reds (compile issues) have been rewritten. Note that the group.Members is still available for backward compatibility.

Thanks @mdryankov for taking care of all that! I'll take a look through your changes.

> Remaining or unfinished stuff:
> 
> 1. Update the legacy endpoints (include members list for get groups & get user groups)
> 2. Rewrite Authman sync from the scratch. The legacy code has been designed to update the entire members list as a single query. Now this is not the case.
> 3. Few membership storage methods look duplicated over time and we need to merge them and remove the useless.

I agree with these points with the exception of rewriting Authman sync completely. I believe the `synchronizeAuthmanGroup` and `syncAuthmanGroupMemberships` functions I reworked to use the new collection should actually be working pretty well at this point. We do still need to rewrite `synchronizeAuthman` and address #213 and #214 as I mentioned before. 

> Perhaps Monday would be a target to finish the rough work and make some integrity checks and test
> 
> P.S I noticed the new membership admin flag. We need to be careful due to the existing clients and I would suggest to pass few back and forth before going in that direction.

The reason for the membership `admin` bool is to be able to use the `storage.SaveGroupMembershipByExternalID` function to update the group memberships with a single operation without needing to pre-load the data for every membership from the database to avoid overwriting the admin status. This will result in considerably less overhead in memory/db operations to either store all the membership records or load each one individually, check the status, then update it. 

I do realize that we will need to be careful to avoid breaking the clients, but I believe this change is worth keeping for this reason. Let me know if you have any other ideas or thoughts on how to handle this. 

Thanks again!

**Comment by mdryankov** [comment]
Hi @shurwit @petyos https://github.com/rokwire/groups-building-block/pull/243 has been introduced for code reviews. Data migration has been already made. However have a saved backup of both collection if we need to repeat the migration process again
