### ISSUE TITLE
[BUG] Unable to create an event for a research project

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/groups-building-block#373]
The issue was originally reported in rokwire/illinois-app#3176

The exact request and the response are listed [here](https://rokwire-workspace.slack.com/archives/CEXARQXQR/p1682503023657419).

The problem was that the POST events request failed with 401 Unauthorized. The token that is used for authorization is fresh  and working. I was an admin of the target research project. Doing the same for a regular group passes successfully. After discussing this with @sandeep-ps we came up with conclusion that most probably the problem is located in Groups BB.

**Comment by sandeep-ps** [comment]
From yesterday's test submission done by Misho, there is only one log entry in the Events BB around that time:
```
2023-04-27T08:22:34.759Z INFO    [Dummy-599 ] : connexion.api.security - ... No auth provided. Aborting with 401.
```
This is usually caused when the validation done by the framework couldn't find the required security method (the access token value in this case). We'll take a closer look.
