### ISSUE TITLE
[BUG] Do not include sub events when loading group events

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/groups-building-block#397]
**Describe the bug**
The V3 API for loading group events includes sub events which must not be included in the response.

**To Reproduce**
1. Open The Illinois app 
2. Go to Browse -> Groups -> All Groups
3. Search for the group "Enrollment Management Event Admins"
4. Tap on "See All Events"
5. See all the 188 events
6. The result includes sub events which should not persist there

**Expected behavior**
The API to return events which are not sub events. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Google Pixel 6
 - Android 13
 - 5.0.77

**Additional context**
This issue is part of the problem described in https://github.com/rokwire/illinois-app/issues/3790 .

Here is the http request and response:

**Request:**
```
POST: https://api.rokwire.illinois.edu/gr/api/group/ce516c66-50a3-41a3-b918-5e7778377aee/events/v3/load

{
  "end_time_after": 1696928973,
  "sort_by": "start_time",
  "order": "asc",
  "offset": 0,
  "limit": 200
}
```

**Response:** (Please see attached .json file)

[group_events_response_prod_20231010.json](https://github.com/rokwire/groups-building-block/files/12856288/group_events_response_prod_20231010.json)

Note: In the example above, the events with `"super_event_id": "6508e08e16fa9f000a507424"` should not be included in the response

**Comment by mdryankov** [comment]
Closing this. It may be reopen if need.
