### ISSUE TITLE
[BUG] Group Event does not have "role" field populated

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/groups-building-block#439]
**Describe the bug**
Group event created with the API `POST: /gr/api/group/P{group_id}/events/v3` does not populate value for the `role` field. 
For example, group admin creates event with the API above and after that adds another user to be `attendance-taker`. The event is visible under group events but the `role` field is not presented in the json response. The result is that the attendance taker does not see "Take Attendance" button.

This is valid when creating events via Groups BB API `POST: /gr/api/group/P{group_id}/events/v3`.
For events created by Calendar BB API `POST: /calendar/api/services/event`

**Expected behavior**
Groups BB to populate the `role` field with the correct value so that when the UIUC client requests API: `POST: /gr/api/group/{group_id}/events/v3/load`.

**Additional context**
This issue is a result of a reported problem in email **Re: University Monday 2024/04/15** from 2024/0417.

Quote:

> 3.2 An issue with Groups BB with the Group Creator and attendance taking. Dobromir/Petyo you can ignore my questions, but follow this and help as needed please.
> 
> This is two ways to see that the issue is perhaps only with the Creator of a Group:
> 
> a) As the Creator of a Public Group with one Assigned Admin, add a new Public Event with Attendance. The take attendance button is not visible.
> 
> b) With the same group as in a) above, the Assigned Admin uses Admin Web to make the Creator an Attendance taker. The take attendance button is not visible.

**Examples**
Event with id: `9345ef22-0181-4e78-a175-a66367686813`

1. The event retrieved from the Admin app:
```
    {
      "all_day": false,
      "attendance_details": {
        "attendance_takers_external_ids": [
          "ddobrev"
        ],
        "is_id_scanning_enabled": true,
        "is_manual_attendance_check_enabled": true
      },
      "attributes": {
        "category": "Other"
      },
      "cancelled": false,
      "contacts": [
        
      ],
      "cost": null,
      "description": "event with test purpose",
      "end": 1713430800,
      "event_type": "online",
      "event_url": null,
      "free": true,
      "grouping": null,
      "id": "9345ef22-0181-4e78-a175-a66367686813",
      "instructions": null,
      "location": null,
      "name": "test event",
      "online_details": {
        "meeting_id": "",
        "meeting_passcode": "",
        "url": "http://google.com"
      },
      "private": false,
      "published": true,
      "registration_details": {
        "external_link": null,
        "label": null,
        "max_event_capacity": null,
        "registrants_external_ids": null,
        "type": "none"
      },
      "speaker": null,
      "sponsor": null,
      "start": 1713387600,
      "survey_details": null,
      "timezone": "Europe/Sofia"
    }
```

2. Event people (`GET: /calendar/api/admin/event/{event_id}/users`)
```
{
  "attendees": [
    
  ],
  "people": [
    {
      "id": "455a2965-be3b-48cf-80d5-2ea4491a7281",
      "identifier": {
        "account_id": "4a9432f7-538a-11ec-923b-0a58a9feac02"
      },
      "registration_type": "creator",
      "role": "admin"
    },
    {
      "id": "4247dc0a-a625-491d-9e7a-b799af0d569e",
      "identifier": {
        "account_id": "",
        "external_id": "ddobrev"
      },
      "registration_type": "attendance-takers-list",
      "role": "attendance-taker"
    }
  ]
}
```

3. Event loaded as `ddobrev` from `POST: /gr/api/group/{group_id}/events/v3/load`
```
    {
      "all_day": false,
      "attendance_details": {
        "attendance_takers_external_ids": [
          "ddobrev"
        ],
        "is_id_scanning_enabled": true,
        "is_manual_attendance_check_enabled": true
      },
      "attributes": {
        "category": "Other"
      },
      "cancelled": false,
      "contacts": [
        
      ],
      "cost": null,
      "data": null,
      "description": "event with test purpose",
      "end": 1713430800,
      "event_type": "online",
      "event_url": null,
      "free": true,
      "grouping": null,
      "id": "9345ef22-0181-4e78-a175-a66367686813",
      "image_url": null,
      "instructions": null,
      "location": null,
      "name": "test event",
      "online_details": {
        "meeting_id": "",
        "meeting_passcode": "",
        "url": "http://google.com"
      },
      "private": false,
      "published": true,
      "registration_details": {
        "external_link": null,
        "label": null,
        "max_event_capacity": null,
        "registrants_external_ids": null,
        "type": "none"
      },
      "source": null,
      "speaker": null,
      "sponsor": null,
      "start": 1713387600,
      "survey_details": null,
      "timezone": "Europe/Sofia"
    }
```

Please note the missing `role`. It should be presented with value `attendance-taker`

**Comment by mdryankov** [comment]
Fixed in #440
