### ISSUE TITLE
[BUG] Populate user's netid when creating group event

### ISSUE THREAD

**Issue by dobromirdobrev** [rokwire/groups-building-block#440]
**Describe the bug**
Group event created in UIUC app does not appear in the Admin app. This is because the API for creating group events `POST: /gr/api/group/{group_id}/events/v3` does not populate the user's net id in the identifier of the user. It only populates the account id.

**Expected behavior**
Populate user's NetID when one creates event via the Groups BB.

**Additional context**
This issue is related to an email **Re: University Monday 2024/04/15** from 2024/04/17.

Quote:

> 3.2 An issue with Groups BB with the Group Creator and attendance taking. Dobromir/Petyo you can ignore my questions, but follow this and help as needed please.
> 
> This is two ways to see that the issue is perhaps only with the Creator of a Group:
> 
> a) As the Creator of a Public Group with one Assigned Admin, add a new Public Event with Attendance. The take attendance button is not visible.
> 
> b) With the same group as in a) above, the Assigned Admin uses Admin Web to make the Creator an Attendance taker. The take attendance button is not visible.

Group id: `dd5565c8-1c15-4734-ae55-c31b6e14166d`
Event id: `b64870f4-3d29-4f70-9a55-d0ffafc35b5e`

This happens only for events created via Groups BB. Events created via Calendar BB works as expected.

**Comment by mdryankov** [comment]
@stefanvit, please check the corresponding Calendar BB API

**Comment by mdryankov** [comment]
Fixed in https://github.com/rokwire/groups-building-block/issues/450
