### ISSUE TITLE
[FEATURE] Include sender, post content and action in group post notification body

### ISSUE THREAD

**Issue by mihail-varbanov** [rokwire/groups-building-block#457]
The current notification for group posts is not quite meaningful and has duplicated data:
```
"subject":"Group - MV Test 3",
"body":"New post has been published in 'MV Test 3' group",
```

Please update the notification body to include the sender, the post content and the action had been taken (e.g. post, reply). Also, the notification for post reply should include only the audience that is involved to that post.

Mode details here: [#4050](https://github.com/rokwire/illinois-app/issues/4050), [#2938](https://github.com/rokwire/illinois-app/issues/2938).

P.S. Do not care for the length of the body text, the client will take care of that.

**Comment by dobromirdobrev** [comment]
I re-open this issue because there are still changes that need to be made. Here they are:

> Please use the double quotation marks ("") instead of single quotation marks ('')

Reference: [Comment](https://github.com/rokwire/illinois-app/issues/4050#issuecomment-2192286724)
