### ISSUE TITLE
[BUG] API members/multi-update not working

### ISSUE THREAD

**Issue by TodorBachvarov** [rokwire/groups-building-block#507]
When calling groupsUrl/group/${group!.id}/members/multi-update the BB returns 200, but the members status remains unchanged (pending). 
This the request I tested with on Dev: 
url: https://api-dev.rokwire.illinois.edu/gr/api/group/e8d53832-dd66-4b5e-af1c-91f8ef2bbf97/members/multi-update
body: {\"user_ids\":[\"eaaa7349-ba71-462c-bd99-d5121622d129\"],\"status\":\"member\"}

**Comment by mdryankov** [comment]
The client is using membership id instead of user_id attribute. Needs to be fixed on client side due to conflict with the names and the real puprose

**Comment by mihail-varbanov** [comment]
After fixing the parameters that the client passes to members/multi-update API everything seems functional. Closing the issue.
